export const DATABASE_PACKAGE = "@aistudy/database" as const;
export * from "./schema/library";
export * from "./schema/courses";
export * from "./schema/goals";
export * from "./schema/identity";
export * from "./schema/preferences";
export * from "./schema/explorations";
export * from "./repositories/library";
export * from "./repositories/course-membership";
export * from "./repositories/identity";
export * from "./repositories/preferences";
export * from "./repositories/opening-learning-preferences";
export * from "./repositories/explorations";
export * from "./migrate";
export * from "./schema/promotions";
export * from "./repositories/promotions";
export * from "./schema/revision-proposals";
export * from "./repositories/revision-proposals";
export * from "./schema/learning-events";
export * from "./repositories/learning-events";
export * from "./schema/cards";
export * from "./repositories/cards";
export * from "./schema/practice-content";
export * from "./repositories/practice-content";
export * from "./repositories/practice-sessions";
export * from "./repositories/backup-restore";
export * from "./migration-preflight";
export * from "./schema/opening-sources";
export * from "./schema/opening-source-chunks";
export * from "./repositories/opening-sources";
export { readOpeningMaterialOrganization } from "./repositories/opening-material-organization";
export { readOpeningSourceContent } from "./repositories/opening-source-content";
export * from "./repositories/opening-source-actions";
export { createOpeningEphemeralProvenanceRepository, EphemeralProvenanceError, type EphemeralProvenanceRepository } from "./repositories/opening-ephemeral-provenance";
export { createOpeningNoteRepository, OpeningNoteError } from "./repositories/opening-note-provenance";
export * from "./repositories/opening-source-chunks";
export * from "./schema/opening-learning";
export * from "./repositories/opening-learning";
export * from "./repositories/opening-conversations";
export * from "./repositories/opening-conversation-selection";
export * from "./schema/opening-jobs";
export * from "./schema/opening-budget";
export * from "./repositories/opening-jobs";
export * from "./repositories/opening-budget";
export * from "./storage/opening-s3";
export { magicMatchesMime } from "./storage/magic";

export * from "./schema/opening-assistant-candidates";
export * from "./repositories/opening-candidates";
export * from "./repositories/opening-tutor-jobs";
export * from "./repositories/opening-context-provenance";

export * from "./schema/opening-memory";
export * from "./repositories/opening-memory";
export * from "./repositories/opening-memory-replace";

export * from "./repositories/opening-privacy";
export * from "./repositories/opening-retests";
export * from "./schema/opening-planning";
export * from "./repositories/opening-plans";
export * from "./repositories/opening-reminders";
export * from "./repositories/opening-connections";
export * from "./repositories/opening-model-providers";
export * from "./schema/opening-connections";
export * from "./storage/opening-credential-vault";
export * from "./repositories/opening-review-candidates";
export * from "./schema/opening-retest-activities";
export * from "./repositories/opening-retest-activities";

export * from "./repositories/opening-learning-evidence-context";
export * from "./repositories/opening-learning-attempts";
export * from "./repositories/opening-learning-read";
export { mapLearningObservation } from "./repositories/opening-learning-facts";
export * from "./schema/opening-learning-attempts";
export * from "./repositories/opening-observation-revisions";

export { createOpeningAiSettingsRepository } from "./repositories/opening-ai-settings";
export { readOpeningCourseLearningHistory } from "./repositories/opening-learning-history-read";
export * from "./repositories/opening-learning-eligibility";
export { readOpeningCourseLearningSummary } from "./repositories/opening-learning-summary-read";
